api/urls.py
from . import views 
from django.urls import path 




urlpatterns = [
    #path('', PostList.as_view(), ),
    #path('<uuid:pk>/', PostDetail.as_view(), ),
    # path('tag/<slug:tag_slug>/',views.post_list,),
    # path('feeds/', views.LatestPostsFeed(), ),
    # path('search/', views.search, )
    path('',views.post_list, name='home')
]

blogx/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include 
from django.conf.urls.static import static
from filebrowser import sites
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions


sitemaps = {
 'posts': PostSitemap,
}

schema_view = get_schema_view(
   openapi.Info(
      title="Blog API",
      default_version='v1',
      description="Description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="dtenny95@gmail.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path("admin/filebrowser/", sites.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path("grappelli/", include("grappelli.urls")),
    path('admin/', admin.site.urls),
    path('', include('blog.urls'), ),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('api/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('main/', include('api.urls')),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('json/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

blog/forms.py
from django import forms 
from tinymce.widgets import TinyMCE
from .models import Post

class TinyMceWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False 

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=TinyMceWidget(
        attrs = {'required':False, 'cols':30, 'rows':30}
    ))
    widget = {
        'id':forms.UUIDField()
    }
    
    class Meta:
        model = Post 
        fields = ('content' , 'img', 'status', 'title', )

class SearchForm(forms.Form):
    query = forms.CharField

templates/pbt/_base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="blogger's website" name="keywords">
    <meta content="fbc blogspot" name="description">
    <title>Fireblog</title>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>



    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>


    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:300;400;600;700;800&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/w3.css' %}" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <div class="sidebar">
            <div class="sidebar-text d-flex flex-column h-100 justify-content-center text-center">
                <img class="mx-auto d-block w-75 bg-primary img-fluid rounded-circle mb-4 p-3"
                    src="{% static 'img/profile.jpg' %}" alt="Image">
                <h1 class="font-weight-bold">Kate Glover</h1>
                <p class="mb-4">

                </p>
                <div class="d-flex justify-content-center mb-5">
                    <a class="btn btn-outline-primary mr-2" href="#"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-primary mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-primary mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                    <a class="btn btn-outline-primary mr-2" href="#"><i class="fab fa-instagram"></i></a>
                </div>
                <a href="" class="btn btn-lg btn-block btn-primary mt-auto">Talk to me</a>
            </div>
            <div class="sidebar-icon d-flex flex-column h-100 justify-content-center text-right">
                <i class="fas fa-2x fa-angle-double-right text-primary"></i>
            </div>
        </div>
        <div class="content">
            <!-- Navbar Start -->
            <div class="container p-0">
                <nav class="w3-bar mt-0  bg-secondary ">
                    <a href="{% url 'home' %}"
                        class="  w3-bar-item nav-link w3-text-white w3-left w3-xlarge font-weight-bold">Fireblog</a>
                    <div>
                        <div class="righty ">
                            <form action="{% url 'search' %}" method="get">
                                <div class="search-box ">
                                    <input type="text" name="query" placeholder="quick search"
                                        class="search-text w3-input w3-text-white " id="id_query">
                                    <a href="#" class="search-btn">
                                        <i class="fas fa-search"></i>
                                    </a>
                                    <style>
                                        .righty {
                                            position: relative;
                                            left: 0;
                                            float: right;
                                        }

                                        .search-box {
                                            transform: translate(-50%, -50%);
                                            height: auto;
                                            border-radius: 40px;
                                            /* right: 50%; */
                                            display: block;
                                            position: relative;
                                            /*padding: 40px;*/
                                        }

                                        .search-box:hover>.search-text {
                                            width: 100px;
                                            padding: 0 6px;
                                            border: 3px solid whitesmoke;
                                            border-radius: 40px;
                                        }

                                        .search-box:hover>.search-btn {
                                            color: rgb(89, 49, 207);
                                            background: whitesmoke;
                                        }

                                        .search-btn {
                                            float: right;
                                            width: 40px;
                                            height: 40px;
                                            border-radius: 50%;
                                            display: flex;
                                            justify-content: center;
                                            align-items: center;
                                            transition: 0.4s;
                                            color: rgb(245, 245, 245);
                                        }

                                        .search-text {
                                            border: none;
                                            background: none;
                                            outline: none;
                                            float: left;
                                            padding: 0;
                                            color: white;
                                            font-size: 16px;
                                            transition: 0.4s;
                                            line-height: 40px;
                                            width: 2px;

                                        }
                                    </style>
                                </div>
                            </form>
                        </div>
                    </div>
                </nav>
            </div>
            <!-- Navbar End -->
            <div>
                {% block content %}
                {% endblock content %}
            </div>
            <div id="" class="font-weight-bold text-primary">
                <h3 class="font-weight-bold text-white container py-4 bg-secondary">Latest posts <span class="w3-right">
                        {% total_posts %} total posts</span></h3>
                {% show_latest_posts 5 %}
            </div>
            <div class="container py-4 bg-secondary text-center">

                <p>
                    <a href="{% url 'feeds' %}" class="w3-text-yellow">Subscribe to my RSS feed</a>
                </p>
                <p class="m-0 text-white">
                    &copy; <a class="text-white font-weight-bold keychainify-checked" href="#">Fireblog</a>. All Rights
                    Reserved. Designed by <a class="text-white font-weight-bold keychainify-checked "
                        href="https://fireportf.herokuapp.com">firebCorps</a>
                </p>
            </div>
        </div>


    </div>
</body>

</html>

templates/pbt/index.html
{% extends 'pbt/_base.html' %}
{% load static %}
{% load blog_tags %}
{% block content %}

<div class="slideshow-container w3-margin">

    <div class="myslides fades ">
        <img class="w-100" src="{% static 'img/carousel-1.jpg' %}" alt="Image">
        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
            <h2 class="mb-3 text-white font-weight-bold">Lorem ipsum dolor sit amet</h2>
            <div class="d-flex text-white">
                <small class="mr-2"><i class="fa fa-calendar-alt"></i> 01-Jan-2045</small>
                <small class="mr-2"><i class="fa fa-folder"></i> Web Design</small>
                <small class="mr-2"><i class="fa fa-comments"></i> 15 Comments</small>
            </div>
           
        </div>
    </div>
    <div class="myslides fades">
        <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
            <h2 class="text-white font-weight-bold">Lorem ipsum dolor sit amet</h2>
            <div class="d-flex">
                <small class="mr-2"><i class="fa fa-calendar-alt"></i> 01-Jan-2045</small>
                <small class="mr-2"><i class="fa fa-folder"></i> Web Design</small>
                <small class="mr-2"><i class="fa fa-comments"></i> 15 Comments</small>
            </div>
            <a href="" class="btn btn-lg btn-outline-light mt-4">Read More</a>
        </div>
    </div>
    <div class="myslides fades">
        <img class="w-100" src="{% static 'img/carousel-3.jpg' %}" alt="Image">
        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
            <h2 class="text-white font-weight-bold">Lorem ipsum dolor sit amet</h2>
            <div class="d-flex">
                <small class="mr-2"><i class="fa fa-calendar-alt"></i> 01-Jan-2045</small>
                <small class="mr-2"><i class="fa fa-folder"></i> Web Design</small>
                <small class="mr-2"><i class="fa fa-comments"></i> 15 Comments</small>
            </div>
            <a href="" class="btn btn-lg btn-outline-light mt-4">Read More</a>
        </div>
    </div>

    <a class="prevs" onclick="pluSSlides(-1)">
        &#10094;
    </a>
    <a class="nexts" onclick="pluSSlides(1)">
        &#10095;
    </a>
    <div style="text-align: center;">
        <span class="dot " onclick="currentSlide(1)"></span>
        <span class="dot " onclick="currentSlide(2)"></span>
        <span class="dot " onclick="currentSlide(3)"></span>
    </div>
</div>


<!-- Blog List Start -->
{% if tag %}
<h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}
{% for article in posts %}
<p class="tags">
    Tags:
    {% for tag in article.tags.all %}
    <a href="{% url 'post_list_by_tag' tag.slug %}" class="w3-large mb-2">
        {{ tag.name }}
    </a>
    {% if not forloop.last %}
    {% endif %}
    {% endfor %}
</p>
<div class="container bg-white pt-5 w3-margin">
    <div class="row blog-item px-3 pb-5">
        <div class="col-md-5">
            {% if article.img %}
            <img class="img-fluid mb-4 mb-md-0" src="{{article.img.url}}" alt="Image">
            {% endif %}
        </div>
        <div class="col-md-7">
            <h3 class="mt-md-4 px-md-3 mb-2 py-2 bg-white font-weight-bold">{{article.title}}</h3>
            <div class="d-flex mb-3">
                <small class="mr-2 text-muted"><i class="fa fa-calendar-alt"></i>{{article.publish}}</small>
                <p><small class="mr-2 text-muted"><i class="fa fa-folder"></i> by {{article.author}}</small></p>
            </div>
            <p>
                {{ article.synopsis|markdown|truncatewords_html:30 }}

            </p>
            <a class="btn btn-link p-0 font-weight-bold py-2" href="{% url 'detail' article.pk %}">Read More <i
                    class="fa fa-angle-right"></i></a>
        </div>
    </div>
</div>
{% endfor %}


<!-- Blog List End -->


<!-- Subscribe Start -->
<div class="container py-5 px-4 bg-secondary text-center">
    <h1 class="text-white font-weight-bold">Subscribe My Newsletter</h1>
    <p class="text-white">Subscribe and get my latest article in your inbox</p>
    <form class="form-inline justify-content-center">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Your Email">
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">Subscribe</button>
            </div>
        </div>
    </form>
</div>
<style>
    .slideshow-container {
        max-width: fit-content;
        position: relative;
        margin: auto;
    }

    .myslides {
        display: none;
    }

    .prevs,
    .nexts {
        cursor: pointer;
        position: absolute;
        top: 50%;
        width: auto;
        margin-top: -22px;
        padding: 16px;
        color: white;
        font-weight: bold;
        font-size: 18px;
        transition: 0.6s ease;
        border-radius: 0 3px 3px 0;
        user-select: none;
    }

    .nexts {
        right: 0;
        border-radius: 3px 0 0 3px;
    }

    .prevs:hover,
    .nexts:hover {
        background-color: rgba(0, 0, 0, .8);
    }

    .dot {
        cursor: pointer;
        height: 15px;
        width: 15px;
        margin: 0 2px;
        background-color: #bbb;
        border-radius: 50%;
        display: inline-block;
        transition: background-color 0.6s ease;
    }


    .actives,
    .dot:hover {
        background-color: #717171;
    }

    .fades {
        animation-name: fades;
        animation-duration: 1.5s;
    }

    @keyframes fades {
        from {
            opacity: .4;
        }

        to {
            opacity: 1;
        }
    }
</style>
<script>
    let slideIndex = 0;
    shoWSlides();

    function shoWSlides(){
        let i;
        let slides = document.getElementsByClassName("myslides");
        for (i = 0; i < slides.length; i++){
            slides[i].style.display = "none";
        }
        slideIndex++;
        if (slideIndex > slides.length){slideIndex = 1}
        slides[slideIndex - 1].style.display = 'block';
        setTimeout(shoWSlides, 5000);
    }
    // let slideIndex = 1;
    // shoWSlides(slideIndex);

    // // Next/previous controls
    // function pluSSlides(n) {
    //     shoWSlides(slideIndex += n);
    // }

    // // Thumbnail image controls
    // function currentSlide(n) {
    //     shoWSlides(slideIndex = n);
    // }

    // function shoWSlides(n) {
    //     let i;
    //     let slides = document.getElementsByClassName("myslides");
    //     let dots = document.getElementsByClassName("dot");
    //     if (n > slides.length) { slideIndex = 1 }
    //     if (n < 1) { slideIndex = slides.length }
    //     for (i = 0; i < slides.length; i++) {
    //         slides[i].style.display = "none";
    //     }
    //     for (i = 0; i < dots.length; i++) {
    //         dots[i].className = dots[i].className.replace(" actives", "");
    //     }
    //     slides[slideIndex - 1].style.display = "block";
    //     dots[slideIndex - 1].className += " actives";
    // }
</script>
<!-- Back to Top -->
<a href="#" class="back-to-top"><i class="fa fa-angle-double-up"></i></a>



{% include "pbt/pagn.html" with page=posts %}
{% endblock content %}

templates/pbt/latest_posts.html
<ul>
    {% for posts in latest_posts %}
    <li>
        <a href="{{ posts.get_absolute_url }}">{{ posts.title }}</a>
    </li>
    {% endfor %}
</ul>

templates/pbt/pagn.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

templates/pbt/search.html
{% extends 'pbt/_base.html' %}
{% load blog_tags %}
{% load static %}
{% block title %}Search{% endblock %}

{% block content %}
{% if query %}
<div class="w3-content w3-margin">
    <p class="w3-xlarge">Search Results</p>

    <p class="w3-large">
        {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
    </p>
    {% for post in results %}
    <div class="w3-margin">
        <i class="w3-xlarge">&rarr;</i>
        <h4 class="w3-xlarge"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {{ post.body|markdown|truncatewords_html:5 }}
        {% empty %}
        <p>No results found</p>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock content %}

templates/pbt/share.html
{% extends "pbt/_base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
{% if sent %}
<h1>E-mail successfully sent</h1>
<p>
    "{{ post.title }}" was successfully sent to {{ form.cleaned_
    data.to }}.
</p>
{% else %}
<h1>Share "{{ post.title }}" by e-mail</h1>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <div>
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    </div>
    {% endfor %}
    <input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock %}

templates/pbt/single.html
{% extends 'pbt/_base.html' %}
{% load blog_tags %}
{% load static %}
{% block content %}
<!-- Page Header Start -->
<div class="container py-5 px-2 bg-primary">
    <div class="row py-5 px-4">
        <div class="col-sm-6 text-center text-md-left">
            <h1 class="mb-3 mb-md-0 text-white text-uppercase font-weight-bold">{{ post.title }}</h1>
        </div>
        <div class="col-sm-6 text-center text-md-right">
            <div class="d-inline-flex pt-2">
                <h4 class="m-0 text-white"><a class="text-white" href="{% url 'home'%}">Home</a></h4>
                <!-- <h4 class="m-0 text-white px-2">/</h4>
                            <h4 class="m-0 text-white">Blog Detail</h4> -->
            </div>
        </div>
    </div>
</div>
<!-- Page Header End -->

<!-- Blog Detail Start -->
<div class="container py-5 px-2 bg-white">
    <div class="row px-4">
        <div class="col-12">
            <img class="img-fluid mb-4" src="{{ post.img.url }}" alt="Image">
            <h2 class="mb-3 font-weight-bold">{{post.synopsis}}</h2>
            <div class="d-flex">
                <p class="mr-3 text-muted"><i class="fa fa-calendar-alt"></i> {{post.publish}} </p>
            </div>
            {{post.content|safe}}
        </div>
        {% for tag in article.tags.all %}
        <div class="col-12 py-4">
            <a href="{% url 'post_list_by_tag' tag.slug %}">
                {{ tag.name }}
            </a>
        </div>
        {% if not forloop.last %}
        {% endif %}
        {% endfor %}
    </div>
</div>
<!-- Blog Detail End -->

<h2 class="font-weight-bold">Similar posts</h2>
{% for post in similar_posts %}
<p>
    <a class="font-weight-bold py-4" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
There are no similar posts yet.
{% endfor %}

<!-- Back to Top -->
<a href="#" class="back-to-top"><i class="fa fa-angle-double-up"></i></a>






{% endblock %}